apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: devopscase  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ylmzzeyneep/newbackend:v1
        ports:
        - containerPort: 5000
        resources:  
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: devopscase  
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5000  
    targetPort: 5000
  type: LoadBalancer
